### ISSUE TITLE
Generiranje Word dokumenta

### ISSUE THREAD

**Issue by stfivic** [elicul/Skriptni_VBA#1]
Istražite kako generirati Word dokumnet (*.docx) iz Excel VBA skripte.

Pogledajte http://excel-macro.tutorialhorizon.com/vba-excel-create-and-save-the-word-document/
Pročitajte i "Related posts" na dnu.

I ovo je slično: http://software-solutions-online.com/vba-write-excel-values-to-word-document/

A ovo je jedna moguća ideja kako koristiti Word predložak: http://stackoverflow.com/questions/26042519/excel-vba-to-open-word-template-populate-then-save-as-docx-file-somewhere-els

**Comment by elicul** [comment]
Dodana je funkcionalnost generiranja .docx i .pdf dokumenata putem botuna
